# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lANZYVov3FaxpZ4LGcs12H2V_iHH05se
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install scrapy

import scrapy

class MySpider(scrapy.Spider):
  name = 'my_spider'
  start_urls = ['https://www.yahoo.com']

  def parse(self, response):
    yield {
        'title':response.css('title::text').get(),
        'paragraphs': response.css('p::text').getall()
    }